version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bloodbank-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4321
      MYSQL_DATABASE: bloodbank
    # map to 3307 on host to avoid collisions with local MySQL
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    container_name: bloodbank-backend
    build:
      context: ./bloodbank-backend
    ports:
      - "9092:9092"   # host:container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bloodbank
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 4321
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    container_name: bloodbank-frontend
    build:
      context: ./bloodbank-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  db_data:
